# Generated by Django 5.1.6 on 2025-03-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuantVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmissao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('valor_diaria', models.FloatField()),
                ('foto', models.ImageField(upload_to='veiculo/')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('data_inspecao', models.DateField()),
                ('data_proxima_inspecao', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.categoriaveiculo')),
                ('quant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.quantveiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.tipoveiculo')),
                ('transmissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.transveiculo')),
            ],
        ),
    ]
